### ISSUE TITLE
Add application in  E2E tests 

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery-nginx-sm#101]
#### Current Behavior

Currently we run e2e tests which run a patternfile(which only installs nginx service mesh)
#### Desired Behavior

We need to a nginx demo application in patternfile format and add that in e2etest
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@jbyers19  Wanna work on it?

**Comment by jbyers19** [comment]
@Revolyssup, perhaps. Not sure when I'll get to it though. Got a lot of other things I'm working on right now.
