### ISSUE TITLE
Change component generation workflow to normalize with other adapters

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery-nginx-sm#112]
#### Current Behavior

Currently the component-generator workflow is stale and fails.
#### Desired Behavior

Use the same workflow as other adapters and generate components by running the adapter.
#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@gr455  will you be able to knock this one out? https://github.com/meshery/meshery-istio/blob/master/.github/workflows/component-generator.yaml Use this as reference

**Comment by gr455** [comment]
> @gr455 will you be able to knock this one out? https://github.com/meshery/meshery-istio/blob/master/.github/workflows/component-generator.yaml Use this as reference

Yep

**Comment by gr455** [comment]
@Revolyssup The component generator workflows for both of the service meshes (Istio and Nginx-SM) look the same
https://github.com/meshery/meshery-nginx-sm/blob/master/.github/workflows/update-oam-defs.yml
https://github.com/meshery/meshery-istio/blob/master/.github/workflows/component-generator.yaml

**Comment by Revolyssup** [comment]
> @Revolyssup The component generator workflows for both of the service meshes (Istio and Nginx-SM) look the same https://github.com/meshery/meshery-nginx-sm/blob/master/.github/workflows/update-oam-defs.yml https://github.com/meshery/meshery-istio/blob/master/.github/workflows/component-generator.yaml

Hmm, I must have been mistaken then. I think we can close this issue.
