### ISSUE TITLE
[Readme] Consistently present Meshery logo

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery-nginx-sm#156]
#### Current State

1> The logo in the readme is not consistent with the one in meshery/meshery repo make it consistent :) 

2> "Join Layer5 Slack!" text in the readme doesn't display properly in dark mode. Fix it.
#### Desired State

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by NPDebs** [comment]
Hi @legendarykamal . Do you mean positioning this logo to the right?

**Comment by legendarykamal** [comment]
no see meshery/meshery or meshery/cilium + check them in dark mode too .

**Comment by NPDebs** [comment]
Oh yeah...I see the discrepancy.
I've got this. 🙂🚀

**Comment by NPDebs** [comment]
Oh yeah...I see the discrepancy.
I've got this. 🙂🚀

**Comment by NPDebs** [comment]
@legendarykamal  I also noticed that the black "Join Layer5 Slack!" text in the readme doesn't display properly in dark mode. Maybe that could be another GFI for Hacktoberfest? 🤔

**Comment by legendarykamal** [comment]
since this is an easy issue we will add it in this only :) let me edit the desc .

**Comment by NPDebs** [comment]
@legendarykamal Cool. 😃 Are you going to open an issue to fix this in the other repos too? Seems like a fun first issue.


I'm done making changes, by the way. 🙂
Could you please assign this to me so I can open a PR? 🙏🏼 Thanks.

**Comment by legendarykamal** [comment]
I have already opened many . 

Sure here you go @NPDebs :white_check_mark:

**Comment by NPDebs** [comment]
Awesome! 🚀  Thank you @legendarykamal 
Off to go snag a few! 😉
