### ISSUE TITLE
[chore] update Go to 1.21, and update relevant pkgs

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery-nginx-sm#257]
### Desired Behaviour
Need to update `Go` to `1.21` in `go.mod` and in `Dockerfile`, and also `Makefile`

- Minor chore on updating `meshkit` and `meshery-adapter-library`

**Comment by ptdatta** [comment]
@saurabh100ni  I would like to take on it.

**Comment by saurabh100ni** [comment]
@Ghat0tkach can you assign @ptdatta to the issue ?

**Comment by harsh098** [comment]
Please assign me this issue @saurabh100ni and @Ghat0tkach

**Comment by saurabh100ni** [comment]
Go on @harsh098 😎✨🚀

**Comment by saurabh100ni** [comment]
@ptdatta do you have any updates with this, if not then we can hand over it to @harsh098

**Comment by ptdatta** [comment]
@saurabh100ni I made a PR 2 months ago for this still it not reviewed.

**Comment by harsh098** [comment]
I have added a review to the PR @theBeginner86
