### ISSUE TITLE
[Read Me] ADD COMMUNITY FORUM

### ISSUE THREAD

**Issue by kumarshobhit** [meshery/meshery-nginx-sm#26]
In the README file of this repo, the link for the community discussion forum has not been added yet.

**Current State:**
![image](https://user-images.githubusercontent.com/58087950/126879850-25c2323b-457a-45ac-bdf5-067f43a2e415.png)

**Desired State:**
![image](https://user-images.githubusercontent.com/58087950/126879715-03df1ebc-a88d-4e29-a167-b9cbd44ccee5.png)

---

I would like to add the above-mentioned link to the README file for the convenience of the developers who are just starting to contribute to this project.

**Comment by leecalcote** [comment]
@kumarshobhit would you like to knock this one out?
