### ISSUE TITLE
to fix error in "Slack Notify on Star" job under GitHub Actions

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery-nginx-sm#262]
## Description
Under **GitHub Actions** of this repository **"[Slack Notify on Star](https://github.com/meshery/meshery-nginx-sm/actions/runs/6325340439)"** job is failing for which [Slack.yaml](https://github.com/meshery/meshery-nginx-sm/blob/master/.github/workflows/slack.yml) is to be Updated.

## Fix
To fix this issue, update the code of [slack.yaml](https://github.com/meshery/meshery-nginx-sm/blob/master/.github/workflows/slack.yml) just by copy/pasting the code from[ slack.yaml](https://github.com/meshery/meshery/blob/master/.github/workflows/slack.yml) of [meshery](https://github.com/meshery/meshery)

**Comment by Aayush987** [comment]
I can work on this issue. Please assign it to me.

**Comment by saurabh100ni** [comment]
Go @Aayush987 😎🚀

**Comment by Aayush987** [comment]
Hi @saurabh100ni , My PR is still waiting for approval. Do I need to do something?

**Comment by saurabh100ni** [comment]
Oh! I see, thanks for bringing this up.

// @ritiksaxena124 @Mohith234 @sudhanshutech @Yashsharma1911
