### ISSUE TITLE
Ensure Consistent Use of MeshKit Errors in meshery-nginx-sm

### ISSUE THREAD

**Issue by singh1203** [meshery/meshery-nginx-sm#288]
#### Current Behavior

Currently, there are instances where errors are being used directly instead of MeshKit errors, which impacts the consistency and quality of error reporting across the project.

#### Desired Behavior

- [ ] Replace all direct usages of errors with MeshKit errors.
- [ ] Ensure that each MeshKit error includes:- Short Description, Long Description, Probable Cause & Suggested Remediation.

#### References
[Meshery Documentation on Meshkit](https://docs.meshery.io/project/contributing/contributing-error)

- Make sure to follow these guidelines during writing Meshkit errors
https://discuss.layer5.io/t/best-practices-for-writing-meshkit-errors/5536

- Also here is an example PR to which you can refer:
[#11340](https://github.com/meshery/meshery/pull/11340)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Sylani-55** [comment]
Hi @singh1203 I'm a beginner and I want to give a try to solving this issue what are prerequisites for solving this issue?? I'm familiar with Error handling in Golang any other things should I learn it would be helpful for me to solve the issue 
Thanks and Regards!!

**Comment by ShivanshuGupta07** [comment]
Hi @singh1203, can I take this one

**Comment by singh1203** [comment]
> Hi @singh1203 I'm a beginner and I want to give a try to solving this issue what are prerequisites for solving this issue?? I'm familiar with Error handling in Golang any other things should I learn it would be helpful for me to solve the issue Thanks and Regards!!

Thanks for your inquiry, @Sylani-55. Please make sure to run the repository locally and review the mentioned documentation.

**Comment by singh1203** [comment]
> Hi @singh1203, can I take this one

Thanks for hopping in @ShivanshuGupta07, but we follow FCFS. Maybe you can review the PR or find similar ones missing in other repositories as well.

**Comment by ShivanshuGupta07** [comment]
> 

No Problem @singh1203, I will definitely try to find some other "good first issue"

**Comment by singh1203** [comment]
@Sylani-55 Just following up, please provide an update on the progress.

**Comment by Sylani-55** [comment]
Hi Sourabh Singh,

Thank you for checking in. I apologize for the delay in resolving the issue. I've been working on it and have made some progress, but I'm not quite finished yet.

I plan to dedicate more time over the next few days and aim to have it completed by this Sunday. I appreciate your understanding and will keep you posted if anything changes.

Please let me know if there's anything else you'd like me to focus on.

Best regards,  
Syed

**Comment by leecalcote** [comment]
@Sylani-55, checking in... it'd be good to get an update on this from you.

**Comment by aarochuk** [comment]
Hello @Sylani-55 @leecalcote is there any update in this ticket I desire to provide assistance or take over the ticket if necessary.

**Comment by leecalcote** [comment]
Not having heard from, @Sylani-55, yes, thank you for raising your hand, @aarochuk.
