### ISSUE TITLE
[bugs] nginx-sm installation 

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-nginx-sm#39]
**Description**
Bugs encountered while installing Nginx-sm using the edge-latest release of Meshery and the adapter installed in cluster.

**1. Meshery server and adapter installed using `mesheryctl`:**

```
time="2021-09-24T10:28:33Z" level=error msg="failed to install CRD crds/circuitbreaker.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User\"system:serviceaccount:meshery:default\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" app=nginx-adaptor code=1006 probable-cause= severity=2 short-description="Error with Nginx installation" suggested-remediation=
```

* **Cause:** Missing `serviceAccount` in manifests downloaded by `mesheryctl` however they're present in the upstream adapter [manifests](https://github.com/meshery/meshery/blob/395259f6f2f541daf973d7454a1a190adcaf41c3/install/deployment_yamls/k8s/meshery-nginx-sm-deployment.yaml#L23)
* **Workaround** Edit the adapter's resource and add `meshery-server` as serviceAccount manually.
* If you apply the above fix which works with other adapters, the adapter tries to install in `meshery` namespace regardless of the namespace specified and even then the nginx-sm init pods fail with errors:
	
	![2021-09-24_16-07](https://user-images.githubusercontent.com/54525605/134661572-8fe06bb0-4751-4ddb-8c82-151af8d03539.png)
	
```
    State:          Terminated
    Reason:       Error
    Exit Code:    1
```

**2. Installing meshery and adpater manifests directly using `kubectl`**
* The same bug you would face when deploying after applying the workaround in the above step.

**3. Installing meshery and adapter using Helm**
* Helm charts for nginx-sm adapter not present.

**Other bugs:**
nginx-sm deployment doesn't show up in Meshery dashboard even though meshsync is receiving the updates.

**Environment:**
 - OS: Linux
 - Meshery: edge-latest
 - Nginx-sm-adapter: edge-latest
 - Environment: kubernetes 1.20.7
 - Nginx-sm version: v1.2.0

**Comment by leecalcote** [comment]
I believe @panyuenlau will be knocking out "3. Installing meshery and adapter using Helm".

**Comment by panyuenlau** [comment]
> I believe @panyuenlau will be knocking out "3. Installing meshery and adapter using Helm".

Yes, I added the missing nginx-sm adapter helm chart in this PR https://github.com/meshery/meshery/pull/4227

**Comment by DelusionalOptimist** [comment]
Were we able to identify the cause behind this and patch it? :thinking: @Revolyssup @utkarsh-pro

**Comment by leecalcote** [comment]
@Revolyssup is this still valid? // @jbyers19

**Comment by jbyers19** [comment]
@leecalcote, yes. I believe the root cause of most of the issues we're seeing is this: https://github.com/helm/helm/issues/8780.

I am in the process of trying to fix this now.
