### ISSUE TITLE
[Docs]The updation of shields is needed in README.md

### ISSUE THREAD

**Issue by Swapnil-Bhabal** [meshery/meshery-nginx-sm#69]
**Current State:**
Small updation of shields in README.md
![image](https://user-images.githubusercontent.com/61308713/146508155-f2d2310e-8989-4bc2-84ec-9117ba4b1f00.png)

**Desired State:**
This is how it should look like
![image](https://user-images.githubusercontent.com/61308713/146508197-84d167a1-0b46-47ca-b0e6-839606186dce.png)

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Swapnil-Bhabal** [comment]
Kindly assign this task to me

**Comment by leecalcote** [comment]
I didn't see this earlier, @Swapnil-Bhabal. Sounds real good.
