### ISSUE TITLE
[CI] Define end-to-end integration test assertions

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-nginx-sm#75]
#### Current Behavior
The following end-to-end integration test workflow has an incomplete definition of test assertions - 

https://github.com/meshery/meshery-nginx-sm/pull/74/files#diff-97b970edb06fde1bf84caf7d208459d2b5e22e8c3166eb9ec6969a321923c9fcR93-R95

#### Desired Behavior
Define end-to-end integration test assertions

#### Acceptance Tests
Passing/failing results should show in Meshery Docs compatibility matrix - https://docs.meshery.io/project/compatibility-matrix (this portion of the workflow is complete already).

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@jbyers19, do you consider the current set of assertions complete?

**Comment by jbyers19** [comment]
Commented on #74 with recommendations for assertions.
