### ISSUE TITLE
Adapter version not displaying in Meshery UI

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-nginx-sm#86]
#### Current Behavior
<img width="335" alt="Screen Shot 2022-01-11 at 5 01 51 PM" src="https://user-images.githubusercontent.com/7570704/149035108-a227b486-bb50-4769-ab5a-43845ae4f3a4.png">

#### Expected Behavior
The release tag (version) should be displayed in this tooltip.

#### Environment

- **Host OS:** Mac
- **Platform:**  Kubernetes
- **Meshery Server Version:** stable-v0.6.0-rc-3
- **Meshery Client Version:** stable-v0.6.0-rc-3
- **Meshery Adapter Version:** ???

Container image digest: sha256:93c2291e83e86d69d9c0838a81b6373cae005910be7298aac65fa2696aa8112d

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Reference - https://hub.docker.com/r/layer5/meshery-nginx-sm/tags

**Comment by leecalcote** [comment]
Is the release tag not being supplied as a golang build flag?

**Comment by leecalcote** [comment]
Last adapter release - https://github.com/meshery/meshery-nginx-sm/actions/runs/1641910412

**Comment by warunicorn19** [comment]
Hey, @jbyers19 would you like to pick this one up?
